name: Version Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: "1.17"

defaults:
  run:
    shell: bash

jobs:

  build_binaries:
    name: Build binary for ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2

      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build with Mage
        id: mage
        uses: magefile/mage-action@v1
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        with:
          version: latest
          args: build:env

      - name: Generate asset for binary
        id: asset
        working-directory: build
        run: |
          zip scraper-${{ steps.semver.outputs.non-prefixed }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip scraper

      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: build/scraper-${{ steps.semver.outputs.non-prefixed }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  publish_release:
    name: Publish release with assets
    needs: build_binaries
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2

      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: assets

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.semver.outputs.non-prefixed }}
          fail_on_unmatched_files: true
          files: |
            scraper-*.zip

  docker_image:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value={{sha}}

      - name: Login to Github Packages
        id: ghcr_login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }})
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
